import { calcular_media} from './utils';
import { cor_emoji_nota } from './ui-utils';

type template_json = (dados: any) => string;

export const listaTemplates_English: Record<string, template_json> = {
    'html': template_html_english,
    'css': template_css_english,
    'python': template_python_english,     
    'javascript': template_javascript_english,
    'typescript': template_typescript_english,
    'c': template_c_english,
    'java': template_java_english,
    'cpp': template_cpp_english,
    'go': template_go_english,
    'csharp': template_csharp_english,
    'lua': template_lua_english,
    'luau': template_luau_english,
    'php': template_php_english,
    'ruby': template_ruby_english,
    'sql': template_sql_english
};

export function template_html_english(dados: any) {
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const media_geral = calcular_media([
        dados.notas.semantica, 
        dados.notas.organizacao, 
        dados.notas.boas_praticas
    ]);

    return `
# 🛡️ Code Review: \`${dados.nome_arquivo}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Semantics** | ${dados.notas.semantica}/10 | ${cor_emoji_nota(dados.notas.semantica)} |
| **Organization** | ${dados.notas.organizacao}/10 | ${cor_emoji_nota(dados.notas.organizacao)} |
| **Best Practices** | ${dados.notas.boas_praticas}/10 | ${cor_emoji_nota(dados.notas.boas_praticas)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 🔍 Detailed Analysis

### 🏗️ Semantics & Structure
${dados.analise_detalhada.semantica.trim()}

### 🏷️ Tag Structure
${dados.analise_detalhada.tags_estrutura.trim()}

### 🎨 Styling
${dados.analise_detalhada.estilos.trim()}

---

## 🚨 Detected Code Smells
${listaSmells}

---

## 💡 Path to Improvement
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
};

export function template_css_english(dados: any) {
    // Process lists with English fallback strings
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.arquitetura || 0,
        dados.notas?.manutenibilidade || 0,
        dados.notas?.especificidade || 0,
        dados.notas?.responsividade || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);
    const usaVar = dados.metricas_css?.usa_variaveis ? "Yes ✅" : "No ❌";

    return `
# 🎨 CSS Code Review: \`${dados.nome_arquivo}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Architecture** | ${dados.notas.arquitetura}/10 | ${cor_emoji_nota(dados.notas.arquitetura)} |
| **Maintainability** | ${dados.notas.manutenibilidade}/10 | ${cor_emoji_nota(dados.notas.manutenibilidade)} |
| **Specificity** | ${dados.notas.especificidade}/10 | ${cor_emoji_nota(dados.notas.especificidade)} |
| **Responsiveness** | ${dados.notas.responsividade}/10 | ${cor_emoji_nota(dados.notas.responsividade)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics
- **\`!important\` Usage:** ${dados.metricas_css?.qtd_important ?? 0} occurrence(s)
- **Selector Depth:** Max of ${dados.metricas_css?.profundidade_maxima ?? 0} levels
- **Uses CSS Variables:** ${usaVar}

---

## 🔍 Detailed Analysis

### 🏗️ Architecture & Selectors
${dados.analise_detalhada.arquitetura_e_seletores?.trim() || "No analysis available."}

### 🛠️ Best Practices & Reuse
${dados.analise_detalhada.boas_praticas_e_reuso?.trim() || "No analysis available."}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
}

export function template_python_english(dados: any) {
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.pep8_compliance || 0,
        dados.notas?.logica_e_eficiencia || 0,
        dados.notas?.modularizacao || 0,
        dados.notas?.tratamento_erros || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    const usaTypeHints = dados.metricas_python?.usa_type_hints ? "Yes ✅" : "No ❌";
    const compCiclomatica = dados.metricas_python?.complexidade_ciclomatica || "Not evaluated";
    const loops = dados.metricas_python?.qtd_loops_aninhados ?? 0;

    return `
# 🐍 Python Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **PEP8 Compliance** | ${dados.notas?.pep8_compliance || 0}/10 | ${cor_emoji_nota(dados.notas?.pep8_compliance || 0)} |
| **Logic & Efficiency** | ${dados.notas?.logica_e_eficiencia || 0}/10 | ${cor_emoji_nota(dados.notas?.logica_e_eficiencia || 0)} |
| **Modularization** | ${dados.notas?.modularizacao || 0}/10 | ${cor_emoji_nota(dados.notas?.modularizacao || 0)} |
| **Error Handling** | ${dados.notas?.tratamento_erros || 0}/10 | ${cor_emoji_nota(dados.notas?.tratamento_erros || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics
- **Cyclomatic Complexity:** ${compCiclomatica}
- **Nested Loops (Max):** ${loops} level(s)
- **Uses Type Hints:** ${usaTypeHints}

---

## 🔍 Detailed Analysis

### 🐍 Pythonic Code
${dados.analise_detalhada?.pythonic_code?.trim() || "_Style analysis not available._"}

### 🛡️ Security & Error Handling
${dados.analise_detalhada?.seguranca_e_erros?.trim() || "_Security analysis not available._"}

---

## ⚠️ Code Smells Found (bad practices or errors affecting code quality)
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
}

export function template_javascript_english(dados: any) {
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.clean_code || 0,
        dados.notas?.performance_assincrona || 0,
        dados.notas?.modularizacao || 0,
        dados.notas?.seguranca || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    const usa_Async_Await = dados.metricas_js?.usa_async_await ? "Yes ✅" : "No ❌";
    const usa_ConstLet = dados.metricas_js?.usa_const_let ? "Yes ✅" : "No ❌ (var usage detected)";
    const compCiclomatica = dados.metricas_js?.complexidade_ciclomatica || "Not evaluated";

    return `
# 🟨 JavaScript Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Clean Code** | ${dados.notas?.clean_code || 0}/10 | ${cor_emoji_nota(dados.notas?.clean_code || 0)} |
| **Async Performance** | ${dados.notas?.performance_assincrona || 0}/10 | ${cor_emoji_nota(dados.notas?.performance_assincrona || 0)} |
| **Modularization (ESM)** | ${dados.notas?.modularizacao || 0}/10 | ${cor_emoji_nota(dados.notas?.modularizacao || 0)} |
| **Security (XSS/Injection)** | ${dados.notas?.seguranca || 0}/10 | ${cor_emoji_nota(dados.notas?.seguranca || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics (Modern JS)
- **Cyclomatic Complexity:** ${compCiclomatica}
- **Uses ES6+ (const/let):** ${usa_ConstLet}
- **Async Patterns (Async/Await):** ${usa_Async_Await}

---

## 🔍 Detailed Analysis

### ⚡ Modern JS & ES6+
${dados.analise_detalhada?.modern_js_analysis?.trim() || "_Modern features analysis not available._"}

### 🔄 Asynchronous Management
${dados.analise_detalhada?.async_error_handling?.trim() || "_Concurrency analysis not available._"}

---

## ⚠️ Code Smells Found (bad practices or errors affecting code quality)
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
}

export function template_typescript_english(dados: any) {
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_clean = parseNota(dados.notas?.clean_code);
    const n_tipos = parseNota(dados.notas?.seguranca_tipos);
    const n_modularizacao = parseNota(dados.notas?.modularizacao);
    const n_seguranca = parseNota(dados.notas?.seguranca);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_clean, n_tipos, n_modularizacao, n_seguranca];
    const media_geral = calcular_media(notasParaMedia);

    const status_any = dados.metricas_ts?.usa_any ? "🚨 Avoid using!" : "✅ Safe";
    const status_interfaces = dados.metricas_ts?.usa_interfaces ? "✅ Defined" : "❌ Define contracts";
    const compCiclomatica = dados.metricas_ts?.complexidade_ciclomatica || "Not evaluated";

    return `
# 🟦 TypeScript Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |
| **Type Safety** | ${n_tipos}/10 | ${cor_emoji_nota(n_tipos)} |
| **Modularization** | ${n_modularizacao}/10 | ${cor_emoji_nota(n_modularizacao)} |
| **General Security** | ${n_seguranca}/10 | ${cor_emoji_nota(n_seguranca)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics (TypeScript)
| Metric | State |
| :--- | :--- |
| **Cyclomatic Complexity** | ${compCiclomatica} |
| **Usage of \`any\`** | ${status_any} |
| **Usage of Interfaces/Types** | ${status_interfaces} |

---

## 🔍 Detailed Analysis

### 🛡️ Type System
${dados.analise_detalhada?.type_system_analysis?.trim() || "_Type analysis not available._"}

### 🔄 Async Management & Error Handling
${dados.analise_detalhada?.async_error_handling?.trim() || "_Concurrency analysis not available._"}

---

## ⚠️ Code Smells Found
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (TS-Engine)_ ♟️
`.trim();
}

export function template_c_english(dados: any) {
    // Process lists with English fallback strings
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.gestao_memoria || 0,
        dados.notas?.performance_velocidade || 0,
        dados.notas?.reutilizacao_recursos || 0,
        dados.notas?.clean_code_c || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    // Low-level metrics status in English
    const status_memoria = dados.metricas_c?.vazamento_memoria_provavel ? "Leak Detected! 💀" : "Safe ✅";
    const status_ponteiros = dados.metricas_c?.uso_ponteiros_perigosos ? "Unsafe Pointers! ⚠️" : "Safe Usage ✅";
    const status_escopo = dados.metricas_c?.poluicao_escopo_global ? "Global Pollution 🚩" : "Clean Scope ✅";
    const status_headers = dados.metricas_c?.possui_header_guards ? "Present ✅" : "Missing ❌";

    return `
# ⚙️ C Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Memory Management** | ${dados.notas?.gestao_memoria || 0}/10 | ${cor_emoji_nota(dados.notas?.gestao_memoria || 0)} |
| **Performance/Speed** | ${dados.notas?.performance_velocidade || 0}/10 | ${cor_emoji_nota(dados.notas?.performance_velocidade || 0)} |
| **Resources/Stack Reuse** | ${dados.notas?.reutilizacao_recursos || 0}/10 | ${cor_emoji_nota(dados.notas?.reutilizacao_recursos || 0)} |
| **Organization (Clean Code)** | ${dados.notas?.clean_code_c || 0}/10 | ${cor_emoji_nota(dados.notas?.clean_code_c || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Low-Level Metrics
- **Memory:** ${status_memoria}
- **Pointers:** ${status_ponteiros}
- **Global Scope:** ${status_escopo}
- **Header Guards:** ${status_headers}

---

## 🔍 Detailed Analysis

### 🧠 Memory Management & Lifecycle
${dados.analise_detalhada?.memory_management_analysis?.trim() || "_Memory analysis not available._"}

### ⚡ Optimization Potential
${dados.analise_detalhada?.optimization_potential?.trim() || "_Performance suggestions not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (C-Engine)_ ♟️
`.trim();
}

export function template_java_english(dados: any) {
    // Process lists with English fallback strings
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.encapsulamento || 0,
        dados.notas?.organizacao_oo || 0,
        dados.notas?.gestao_recursos || 0,
        dados.notas?.clean_code_java || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    // Architectural status in English
    const status_modificadores = dados.metricas_java?.uso_correto_modificadores ? "Protected ✅" : "Exposed 🚨 (Use private)";
    const status_naming = dados.metricas_java?.segue_padroes_naming ? "Java Standards ✅" : "Off-Standard ❌";
    const status_recursos = dados.metricas_java?.vazamento_recursos_io ? "Leak Detected! ⚠️" : "Resources Closed ✅";
    const complexidade_oo = dados.metricas_java?.complexidade_oo || "Not evaluated";

    return `
# ☕ Java Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Encapsulation** | ${dados.notas?.encapsulamento || 0}/10 | ${cor_emoji_nota(dados.notas?.encapsulamento || 0)} |
| **OO Organization** | ${dados.notas?.organizacao_oo || 0}/10 | ${cor_emoji_nota(dados.notas?.organizacao_oo || 0)} |
| **Resource Management** | ${dados.notas?.gestao_recursos || 0}/10 | ${cor_emoji_nota(dados.notas?.gestao_recursos || 0)} |
| **Java Clean Code** | ${dados.notas?.clean_code_java || 0}/10 | ${cor_emoji_nota(dados.notas?.clean_code_java || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Architecture Metrics (JVM)
- **Access Modifiers:** ${status_modificadores}
- **Naming Conventions:** ${status_naming}
- **I/O Leak (Streams):** ${status_recursos}
- **OO Complexity:** ${complexidade_oo}

---

## 🔍 Detailed Analysis

### 🏗️ Design & Object Orientation
${dados.analise_detalhada?.oo_analysis?.trim() || "_OO analysis not available._"}

### 🚀 Resource Efficiency & Performance
${dados.analise_detalhada?.resource_efficiency?.trim() || "_Efficiency analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (Java-Engine)_ ♟️
`.trim();
}

export function template_cpp_english(dados: any) {
    // Process lists with English fallback strings
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.raii_memoria || 0,
        dados.notas?.eficiencia_copias || 0,
        dados.notas?.uso_stl || 0,
        dados.notas?.clean_code_cpp || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    // Performance and Safety status in English
    const status_smart_ptr = dados.metricas_cpp?.usa_smart_pointers ? "RAII/Smart Pointers ✅" : "Raw Pointers ⚠️";
    const status_ref = dados.metricas_cpp?.usa_passagem_por_ref ? "Efficient Passing ✅" : "Heavy Copying 🚨";
    const status_stl = dados.metricas_cpp?.evita_recursos_c_puros ? "STL Utilized ✅" : "Legacy C Features 🚩";
    const complexidade = dados.metricas_cpp?.complexidade_modelo || "Not evaluated";

    return `
# 🧊 C++ Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **RAII & Memory** | ${dados.notas?.raii_memoria || 0}/10 | ${cor_emoji_nota(dados.notas?.raii_memoria || 0)} |
| **Efficiency (Copies)** | ${dados.notas?.eficiencia_copias || 0}/10 | ${cor_emoji_nota(dados.notas?.eficiencia_copias || 0)} |
| **STL Usage** | ${dados.notas?.uso_stl || 0}/10 | ${cor_emoji_nota(dados.notas?.uso_stl || 0)} |
| **C++ Clean Code** | ${dados.notas?.clean_code_cpp || 0}/10 | ${cor_emoji_nota(dados.notas?.clean_code_cpp || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Performance & Safety Metrics
- **Memory Management:** ${status_smart_ptr}
- **Parameter Optimization:** ${status_ref}
- **Containers/STL:** ${status_stl}
- **Model Complexity:** ${complexidade}

---

## 🔍 Detailed Analysis

### 🛡️ Memory Safety (RAII)
${dados.analise_detalhada?.memory_safety_analysis?.trim() || "_Safety analysis not available._"}

### 🚀 Optimization & Modern C++
${dados.analise_detalhada?.modern_cpp_optimization?.trim() || "_Optimization suggestions not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (CPP-Engine)_ ♟️
`.trim();
}

export function template_go_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_erros = parseNota(dados.notas?.tratamento_erros);
    const n_concorrencia = parseNota(dados.notas?.concorrencia);
    const n_idiomaticidade = parseNota(dados.notas?.idiomaticidade);
    const n_performance = parseNota(dados.notas?.performance);
    const n_clean = parseNota(dados.notas?.clean_code_go);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_erros, n_concorrencia, n_idiomaticidade, n_performance, n_clean];
    const media_geral = calcular_media(notasParaMedia);

    // Runtime Metrics status in English
    const status_erros = dados.metricas_go?.trata_todos_erros ? "Handled ✅" : "Ignored 🚨";
    const status_defer = dados.metricas_go?.usa_defer_corretamente ? "Correct ✅" : "Leak Risk ⚠️";
    const status_concorrencia = dados.metricas_go?.concorrencia_segura ? "Safe ✅" : "Deadlock Risk 🚩";
    const status_ctx = dados.metricas_go?.usa_contexto ? "Propagated ✅" : "Missing ❌";
    const estilo = dados.metricas_go?.estilo_codigo || "Not evaluated";

    return `
# 🐹 Go Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Error Handling** | ${n_erros}/10 | ${cor_emoji_nota(n_erros)} |
| **Concurrency** | ${n_concorrencia}/10 | ${cor_emoji_nota(n_concorrencia)} |
| **Idiomaticity** | ${n_idiomaticidade}/10 | ${cor_emoji_nota(n_idiomaticidade)} |
| **Performance** | ${n_performance}/10 | ${cor_emoji_nota(n_performance)} |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Runtime Metrics (Go)
| Metric | State |
| :--- | :--- |
| **Errors** | ${status_erros} |
| **Defer/Resources** | ${status_defer} |
| **Concurrency** | ${status_concorrencia} |
| **Context** | ${status_ctx} |
| **Style** | ${estilo} |

---

## 🔍 Detailed Analysis

### ⚠️ Robustness & Errors
${dados.analise_detalhada?.error_handling_analysis?.trim() || "_Error analysis not available._"}

### 🔄 Orchestration (Goroutines/Channels)
${dados.analise_detalhada?.concurrency_design?.trim() || "_Concurrency analysis not available._"}

### ⚡ Memory & Performance
${dados.analise_detalhada?.memory_and_performance?.trim() || "_Performance analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (Go-Engine)_ ♟️
`.trim();
}

export function template_csharp_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_async = parseNota(dados.notas?.async_await);
    const n_recursos = parseNota(dados.notas?.gestao_recursos);
    const n_linq = parseNota(dados.notas?.linq_performance);
    const n_clean = parseNota(dados.notas?.clean_code_csharp);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_async, n_recursos, n_linq, n_clean];
    const media_geral = calcular_media(notasParaMedia);

    // .NET Runtime Metrics status in English
    const status_async = dados.metricas_csharp?.concorrencia_async_segura ? "Safe ✅" : "Deadlock Risk 🚩";
    const status_using = dados.metricas_csharp?.libera_recursos_using ? "IDisposable OK ✅" : "Leak Risk ⚠️";
    const status_linq = dados.metricas_csharp?.linq_otimizado ? "Optimized ✅" : "Lazy Evaluation Warning ⚠️";
    const nivel = dados.metricas_csharp?.nivel_linguagem || "Not evaluated";

    return `
# 💜 C# Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Async/Await** | ${n_async}/10 | ${cor_emoji_nota(n_async)} |
| **Resource Management** | ${n_recursos}/10 | ${cor_emoji_nota(n_recursos)} |
| **LINQ/Performance** | ${n_linq}/10 | ${cor_emoji_nota(n_linq)} |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Runtime Metrics (.NET)
| Metric | State |
| :--- | :--- |
| **Concurrency** | ${status_async} |
| **Resources (Using)** | ${status_using} |
| **LINQ/Collections** | ${status_linq} |
| **.NET Version Level** | ${nivel} |

---

## 🔍 Detailed Analysis

### 🔄 Async & Concurrency
${dados.analise_detalhada?.async_and_concurrency?.trim() || "_Async analysis not available._"}

### ⚡ Memory & LINQ
${dados.analise_detalhada?.memory_and_linq?.trim() || "_Memory and LINQ analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (CSharp-Engine)_ ♟️
`.trim();
}

export function template_lua_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_escopo = parseNota(dados.notas?.escopo_variaveis);
    const n_tabelas = parseNota(dados.notas?.eficiencia_tabelas);
    const n_erros = parseNota(dados.notas?.tratamento_erros);
    const n_idiomatico = parseNota(dados.notas?.idiomaticidade);
    const n_perf = parseNota(dados.notas?.performance_geral);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_escopo, n_tabelas, n_erros, n_idiomatico, n_perf];
    const media_geral = calcular_media(notasParaMedia);

    // Lua Runtime Metrics status in English
    const status_locais = dados.metricas_lua?.usa_apenas_locais ? "Safe ✅" : "Globals Detected 🚨";
    const status_concat = dados.metricas_lua?.usa_table_concat ? "Optimized ✅" : "Inefficient Concat. ⚠️";
    const status_meta = dados.metricas_lua?.metatables_seguras ? "Safe ✅" : "Metatable Risk 🚩";
    const status_erros = dados.metricas_lua?.tratamento_falhas_seguro ? "Handled ✅" : "Crash Risk ❌";
    const versao = dados.metricas_lua?.versao_compativel || "Not specified";

    return `
# 🌙 Lua Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Scope (Local)** | ${n_escopo}/10 | ${cor_emoji_nota(n_escopo)} |
| **Table Efficiency** | ${n_tabelas}/10 | ${cor_emoji_nota(n_tabelas)} |
| **Error Handling** | ${n_erros}/10 | ${cor_emoji_nota(n_erros)} |
| **Idiomaticity** | ${n_idiomatico}/10 | ${cor_emoji_nota(n_idiomatico)} |
| **Performance** | ${n_perf}/10 | ${cor_emoji_nota(n_perf)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Runtime Metrics (Lua)
| Metric | State |
| :--- | :--- |
| **Global Usage** | ${status_locais} |
| **Concatenation** | ${status_concat} |
| **Metatables** | ${status_meta} |
| **Failure Handling** | ${status_erros} |
| **Version** | ${versao} |

---

## 🔍 Detailed Analysis

### 📦 Scope & Memory
${dados.analise_detalhada?.scope_and_memory?.trim() || "_Scope analysis not available._"}

### 🛡️ Errors & Safety
${dados.analise_detalhada?.error_handling_and_safety?.trim() || "_Error analysis not available._"}

### 🌙 Idiomatic Patterns
${dados.analise_detalhada?.lua_idiomatic_patterns?.trim() || "_Idiomatic analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (Lua-Engine)_ ♟️
`.trim();
}

export function template_luau_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_type = parseNota(dados.notas?.type_safety);
    const n_eng = parseNota(dados.notas?.engine_performance);
    const n_mem = parseNota(dados.notas?.memory_management);
    const n_mod = parseNota(dados.notas?.modern_syntax);
    const n_err = parseNota(dados.notas?.error_handling);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_type, n_eng, n_mem, n_mod, n_err];
    const media_geral = calcular_media(notasParaMedia);

    // Luau Runtime Metrics status in English
    const status_strict = dados.metricas_luau?.usa_strict_typing ? "Strict ✅" : "Non-strict/Default ⚠️";
    const status_task = dados.metricas_luau?.usa_task_library_apenas ? "Task Lib ✅" : "Legacy wait() 🚨";
    const status_falhas = dados.metricas_luau?.trata_falhas_roblox ? "Safe ✅" : "Crash Risk ❌";
    const status_conexoes = dados.metricas_luau?.conexoes_seguras ? "Disconnected ✅" : "Leak Risk 🚩";
    const estilo = dados.metricas_luau?.estilo_codigo || "Not evaluated";

    return `
# 🚀 Luau Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Type Safety** | ${n_type}/10 | ${cor_emoji_nota(n_type)} |
| **Engine Performance** | ${n_eng}/10 | ${cor_emoji_nota(n_eng)} |
| **Memory Management** | ${n_mem}/10 | ${cor_emoji_nota(n_mem)} |
| **Modern Syntax** | ${n_mod}/10 | ${cor_emoji_nota(n_mod)} |
| **Error Handling** | ${n_err}/10 | ${cor_emoji_nota(n_err)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Runtime Metrics (Luau)
| Metric | State |
| :--- | :--- |
| **Strict Typing** | ${status_strict} |
| **Task Library** | ${status_task} |
| **Roblox Failures** | ${status_falhas} |
| **Connections** | ${status_conexoes} |
| **Style** | ${estilo} |

---

## 🔍 Detailed Analysis

### 🛡️ Architecture & Typing
${dados.analise_detalhada?.types_and_architecture?.trim() || "_Analysis not available._"}

### ⚙️ Engine Interactions (Roblox)
${dados.analise_detalhada?.roblox_engine_interactions?.trim() || "_Analysis not available._"}

### 🌙 Modern Luau Opportunities
${dados.analise_detalhada?.luau_syntax_opportunities?.trim() || "_Analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (Luau-Engine)_ ♟️
`.trim();
}

export function template_php_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_type = parseNota(dados.notas?.type_safety);
    const n_seg = parseNota(dados.notas?.seguranca_web);
    const n_arq = parseNota(dados.notas?.arquitetura_psr);
    const n_mod = parseNota(dados.notas?.modern_syntax);
    const n_clean = parseNota(dados.notas?.clean_code);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_type, n_seg, n_arq, n_mod, n_clean];
    const media_geral = calcular_media(notasParaMedia);

    // PHP Runtime Metrics status in English
    const status_strict = dados.metricas_php?.usa_strict_types ? "Strict ✅" : "Weak/Unsafe ⚠️";
    const status_pdo = dados.metricas_php?.db_seguro_pdo ? "PDO OK ✅" : "SQL Injection Risk 🚨";
    const status_debug = dados.metricas_php?.sem_var_dump_die ? "Clean ✅" : "Debug Artifacts ❌";
    const status_arq = dados.metricas_php?.arquitetura_moderna ? "PSR/OOP ✅" : "Spaghetti Code 🚩";
    const versao = dados.metricas_php?.versao_estimada || "Not identified";

    return `
# 🐘 PHP Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Type Safety** | ${n_type}/10 | ${cor_emoji_nota(n_type)} |
| **Web Security** | ${n_seg}/10 | ${cor_emoji_nota(n_seg)} |
| **Architecture (PSR)** | ${n_arq}/10 | ${cor_emoji_nota(n_arq)} |
| **Modern Syntax** | ${n_mod}/10 | ${cor_emoji_nota(n_mod)} |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Runtime Metrics (PHP)
| Metric | State |
| :--- | :--- |
| **Strict Types** | ${status_strict} |
| **SQL (PDO)** | ${status_pdo} |
| **Clean Debug** | ${status_debug} |
| **Architecture** | ${status_arq} |
| **Version** | ${versao} |

---

## 🔍 Detailed Analysis

### 🛡️ Security & Types
${dados.analise_detalhada?.security_and_types?.trim() || "_Analysis not available._"}

### 🏗️ Architecture & Standards (PSR)
${dados.analise_detalhada?.architecture_and_standards?.trim() || "_Analysis not available._"}

### ⚡ Modernization Opportunities (PHP 8+)
${dados.analise_detalhada?.php_modernization_opportunities?.trim() || "_Analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (PHP-Engine)_ ♟️
`.trim();
}

export function template_ruby_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_idio = parseNota(dados.notas?.ruby_idiomatic);
    const n_perf = parseNota(dados.notas?.activerecord_perf);
    const n_seg = parseNota(dados.notas?.seguranca);
    const n_oop = parseNota(dados.notas?.arquitetura_oop);
    const n_clean = parseNota(dados.notas?.clean_code);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_idio, n_perf, n_seg, n_oop, n_clean];
    const media_geral = calcular_media(notasParaMedia);

    // Ruby Runtime Metrics status in English
    const status_n1 = dados.metricas_ruby?.sem_n_plus_one ? "Optimized ✅" : "N+1 Query Risk ⚠️";
    const status_orm = dados.metricas_ruby?.orm_seguro ? "Safe ✅" : "SQL Injection Risk 🚨";
    const status_debug = dados.metricas_ruby?.sem_debug_code ? "Clean ✅" : "Debug Artifacts (Pry) ❌";
    const status_oop = dados.metricas_ruby?.arquitetura_desacoplada ? "SOLID/DRY ✅" : "Spaghetti Code 🚩";
    const versao = dados.metricas_ruby?.versao_estimada || "Not identified";

    return `
# 💎 Ruby Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Ruby Idiomatic** | ${n_idio}/10 | ${cor_emoji_nota(n_idio)} |
| **ActiveRecord Perf** | ${n_perf}/10 | ${cor_emoji_nota(n_perf)} |
| **Security** | ${n_seg}/10 | ${cor_emoji_nota(n_seg)} |
| **OOP Architecture** | ${n_oop}/10 | ${cor_emoji_nota(n_oop)} |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Runtime Metrics (Ruby)
| Metric | State |
| :--- | :--- |
| **N+1 Queries** | ${status_n1} |
| **Safe ORM** | ${status_orm} |
| **Clean Debug** | ${status_debug} |
| **Architecture** | ${status_oop} |
| **Version** | ${versao} |

---

## 🔍 Detailed Analysis

### 💎 Idiomatic Patterns (Rubyism)
${dados.analise_detalhada?.idiomatic_patterns?.trim() || "_Analysis not available._"}

### 🛡️ ActiveRecord & Security
${dados.analise_detalhada?.activerecord_and_security?.trim() || "_Analysis not available._"}

### 🏗️ Architecture & Refactoring
${dados.analise_detalhada?.architecture_and_refactoring?.trim() || "_Analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (Ruby-Engine)_ ♟️
`.trim();
}

export function template_sql_english(dados: any) {
    // 🛡️ Helper to sanitize scores (removes "/10" and ensures number)
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_perf = parseNota(dados.notas?.performance_sargability);
    const n_arq = parseNota(dados.notas?.arquitetura_legibilidade);
    const n_conc = parseNota(dados.notas?.concorrencia_integridade);
    const n_seg = parseNota(dados.notas?.seguranca);
    const n_clean = parseNota(dados.notas?.clean_code_sql);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_perf, n_arq, n_conc, n_seg, n_clean];
    const media_geral = calcular_media(notasParaMedia);

    // Database Metrics status in English
    const status_sarg = dados.metricas_sql?.query_sargable ? "Sargable ✅" : "Full Scan Risk ⚠️";
    const status_cte = dados.metricas_sql?.usa_ctes ? "Modular (CTE) ✅" : "Subqueries ⚠️";
    const status_sqli = dados.metricas_sql?.protegido_sqli ? "Safe ✅" : "SQL Injection 🚨";
    const status_trans = dados.metricas_sql?.transacional_seguro ? "Transactional ✅" : "Auto-commit 🚩";
    const dialect = dados.metricas_sql?.dialect || "Not identified";

    const analise_plan = dados.analise_detalhada?.execution_plan_analysis;
    const analise_conc = dados.analise_detalhada?.concurrency_and_locks || dados.analise_detalhada?.concurrency_and_locksy;
    const analise_schema = dados.analise_detalhada?.schema_and_types || dados.analise_detalhada?.architecture_and_refactoring;

    return `
# 🗄️ SQL Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Performance (Sargability)** | ${n_perf}/10 | ${cor_emoji_nota(n_perf)} |
| **Architecture & Readability** | ${n_arq}/10 | ${cor_emoji_nota(n_arq)} |
| **Concurrency & Integrity** | ${n_conc}/10 | ${cor_emoji_nota(n_conc)} |
| **Security (SQLi)** | ${n_seg}/10 | ${cor_emoji_nota(n_seg)} |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Database Metrics (SQL)
| Metric | State |
| :--- | :--- |
| **Query Sargability** | ${status_sarg} |
| **CTE Usage** | ${status_cte} |
| **SQLi Protection** | ${status_sqli} |
| **Transactions** | ${status_trans} |
| **Dialect** | ${dialect} |

---

## 🔍 Detailed Analysis

### ⚡ Execution Plan & Indexes
${analise_plan?.trim() || "_Execution analysis not available._"}

### 🔒 Concurrency, Locks & Transactions
${analise_conc?.trim() || "_Concurrency analysis not available._"}

### 🏗️ Schema, Types & Architecture
${analise_schema?.trim() || "_Architecture analysis not available._"}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (SQL-Engine)_ ♟️
`.trim();
}