import { calcular_media} from './utils';
import { cor_emoji_nota } from './ui-utils';

type template_json = (dados: any) => string;

export const listaTemplates_English: Record<string, template_json> = {
    'html': template_html_english,
    'css': template_css_english,
    'python': template_python_english,     
    'javascript': template_javascript_english,
    'typescript': template_typescript_english,
    'c': template_c,
    'java': template_java,
    'cpp': template_cpp,
    'go': template_go,
    'csharp': template_csharp,
    'lua': template_lua,
    'luau': template_luau,
    'php': template_php,
    'ruby': template_ruby,
    'sql': template_sql
};

export function template_html_english(dados: any) {
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const media_geral = calcular_media([
        dados.notas.semantica, 
        dados.notas.organizacao, 
        dados.notas.boas_praticas
    ]);

    return `
# 🛡️ Code Review: \`${dados.nome_arquivo}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Semantics** | ${dados.notas.semantica}/10 | ${cor_emoji_nota(dados.notas.semantica)} |
| **Organization** | ${dados.notas.organizacao}/10 | ${cor_emoji_nota(dados.notas.organizacao)} |
| **Best Practices** | ${dados.notas.boas_praticas}/10 | ${cor_emoji_nota(dados.notas.boas_praticas)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 🔍 Detailed Analysis

### 🏗️ Semantics & Structure
${dados.analise_detalhada.semantica.trim()}

### 🏷️ Tag Structure
${dados.analise_detalhada.tags_estrutura.trim()}

### 🎨 Styling
${dados.analise_detalhada.estilos.trim()}

---

## 🚨 Detected Code Smells
${listaSmells}

---

## 💡 Path to Improvement
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
};

export function template_css_english(dados: any) {
    // Process lists with English fallback strings
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.arquitetura || 0,
        dados.notas?.manutenibilidade || 0,
        dados.notas?.especificidade || 0,
        dados.notas?.responsividade || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);
    const usaVar = dados.metricas_css?.usa_variaveis ? "Yes ✅" : "No ❌";

    return `
# 🎨 CSS Code Review: \`${dados.nome_arquivo}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Architecture** | ${dados.notas.arquitetura}/10 | ${cor_emoji_nota(dados.notas.arquitetura)} |
| **Maintainability** | ${dados.notas.manutenibilidade}/10 | ${cor_emoji_nota(dados.notas.manutenibilidade)} |
| **Specificity** | ${dados.notas.especificidade}/10 | ${cor_emoji_nota(dados.notas.especificidade)} |
| **Responsiveness** | ${dados.notas.responsividade}/10 | ${cor_emoji_nota(dados.notas.responsividade)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics
- **\`!important\` Usage:** ${dados.metricas_css?.qtd_important ?? 0} occurrence(s)
- **Selector Depth:** Max of ${dados.metricas_css?.profundidade_maxima ?? 0} levels
- **Uses CSS Variables:** ${usaVar}

---

## 🔍 Detailed Analysis

### 🏗️ Architecture & Selectors
${dados.analise_detalhada.arquitetura_e_seletores?.trim() || "No analysis available."}

### 🛠️ Best Practices & Reuse
${dados.analise_detalhada.boas_praticas_e_reuso?.trim() || "No analysis available."}

---

## ⚠️ Found Code Smells
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
}

export function template_python_english(dados: any) {
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.pep8_compliance || 0,
        dados.notas?.logica_e_eficiencia || 0,
        dados.notas?.modularizacao || 0,
        dados.notas?.tratamento_erros || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    const usaTypeHints = dados.metricas_python?.usa_type_hints ? "Yes ✅" : "No ❌";
    const compCiclomatica = dados.metricas_python?.complexidade_ciclomatica || "Not evaluated";
    const loops = dados.metricas_python?.qtd_loops_aninhados ?? 0;

    return `
# 🐍 Python Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **PEP8 Compliance** | ${dados.notas?.pep8_compliance || 0}/10 | ${cor_emoji_nota(dados.notas?.pep8_compliance || 0)} |
| **Logic & Efficiency** | ${dados.notas?.logica_e_eficiencia || 0}/10 | ${cor_emoji_nota(dados.notas?.logica_e_eficiencia || 0)} |
| **Modularization** | ${dados.notas?.modularizacao || 0}/10 | ${cor_emoji_nota(dados.notas?.modularizacao || 0)} |
| **Error Handling** | ${dados.notas?.tratamento_erros || 0}/10 | ${cor_emoji_nota(dados.notas?.tratamento_erros || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics
- **Cyclomatic Complexity:** ${compCiclomatica}
- **Nested Loops (Max):** ${loops} level(s)
- **Uses Type Hints:** ${usaTypeHints}

---

## 🔍 Detailed Analysis

### 🐍 Pythonic Code
${dados.analise_detalhada?.pythonic_code?.trim() || "_Style analysis not available._"}

### 🛡️ Security & Error Handling
${dados.analise_detalhada?.seguranca_e_erros?.trim() || "_Security analysis not available._"}

---

## ⚠️ Code Smells Found (bad practices or errors affecting code quality)
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
}

export function template_javascript_english(dados: any) {
    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [
        dados.notas?.clean_code || 0,
        dados.notas?.performance_assincrona || 0,
        dados.notas?.modularizacao || 0,
        dados.notas?.seguranca || 0
    ];
    
    const media_geral = calcular_media(notasParaMedia);

    const usa_Async_Await = dados.metricas_js?.usa_async_await ? "Yes ✅" : "No ❌";
    const usa_ConstLet = dados.metricas_js?.usa_const_let ? "Yes ✅" : "No ❌ (var usage detected)";
    const compCiclomatica = dados.metricas_js?.complexidade_ciclomatica || "Not evaluated";

    return `
# 🟨 JavaScript Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Clean Code** | ${dados.notas?.clean_code || 0}/10 | ${cor_emoji_nota(dados.notas?.clean_code || 0)} |
| **Async Performance** | ${dados.notas?.performance_assincrona || 0}/10 | ${cor_emoji_nota(dados.notas?.performance_assincrona || 0)} |
| **Modularization (ESM)** | ${dados.notas?.modularizacao || 0}/10 | ${cor_emoji_nota(dados.notas?.modularizacao || 0)} |
| **Security (XSS/Injection)** | ${dados.notas?.seguranca || 0}/10 | ${cor_emoji_nota(dados.notas?.seguranca || 0)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics (Modern JS)
- **Cyclomatic Complexity:** ${compCiclomatica}
- **Uses ES6+ (const/let):** ${usa_ConstLet}
- **Async Patterns (Async/Await):** ${usa_Async_Await}

---

## 🔍 Detailed Analysis

### ⚡ Modern JS & ES6+
${dados.analise_detalhada?.modern_js_analysis?.trim() || "_Modern features analysis not available._"}

### 🔄 Asynchronous Management
${dados.analise_detalhada?.async_error_handling?.trim() || "_Concurrency analysis not available._"}

---

## ⚠️ Code Smells Found (bad practices or errors affecting code quality)
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer_ ♟️
`.trim();
}

export function template_typescript_english(dados: any) {
    const parseNota = (nota: any) => {
        const num = parseFloat(String(nota).replace(/\/10/g, '').trim());
        return isNaN(num) ? 0 : num;
    };

    const n_clean = parseNota(dados.notas?.clean_code);
    const n_tipos = parseNota(dados.notas?.seguranca_tipos);
    const n_modularizacao = parseNota(dados.notas?.modularizacao);
    const n_seguranca = parseNota(dados.notas?.seguranca);

    const listaSugestoes = dados.sugestoes_refatoracao
        ?.map((s: string) => `- 💡 ${s?.trim() || "Empty suggestion"}`)
        .join('\n') || "_No suggestions at the moment._";

    const listaSmells = dados.code_smells_encontrados
        ?.map((s: string) => `- 🚨 ${s?.trim() || "Unspecified issue"}`)
        .join('\n') || "_No serious issues detected._";

    const notasParaMedia = [n_clean, n_tipos, n_modularizacao, n_seguranca];
    const media_geral = calcular_media(notasParaMedia);

    const status_any = dados.metricas_ts?.usa_any ? "🚨 Avoid using!" : "✅ Safe";
    const status_interfaces = dados.metricas_ts?.usa_interfaces ? "✅ Defined" : "❌ Define contracts";
    const compCiclomatica = dados.metricas_ts?.complexidade_ciclomatica || "Not evaluated";

    return `
# 🟦 TypeScript Code Review: \`${dados.nome_arquivo || "unknown_file"}\`

| Criterion | Score | Status |
| :--- | :---: | :---: |
| **Clean Code** | ${n_clean}/10 | ${cor_emoji_nota(n_clean)} |
| **Type Safety** | ${n_tipos}/10 | ${cor_emoji_nota(n_tipos)} |
| **Modularization** | ${n_modularizacao}/10 | ${cor_emoji_nota(n_modularizacao)} |
| **General Security** | ${n_seguranca}/10 | ${cor_emoji_nota(n_seguranca)} |

---

## 📊 Overall Rating: \`${media_geral.toFixed(2)}/10\` ${cor_emoji_nota(media_geral)}

## 📏 Technical Metrics (TypeScript)
| Metric | State |
| :--- | :--- |
| **Cyclomatic Complexity** | ${compCiclomatica} |
| **Usage of \`any\`** | ${status_any} |
| **Usage of Interfaces/Types** | ${status_interfaces} |

---

## 🔍 Detailed Analysis

### 🛡️ Type System
${dados.analise_detalhada?.type_system_analysis?.trim() || "_Type analysis not available._"}

### 🔄 Async Management & Error Handling
${dados.analise_detalhada?.async_error_handling?.trim() || "_Concurrency analysis not available._"}

---

## ⚠️ Code Smells Found
${listaSmells}

## 🚀 Refactoring Suggestions
${listaSugestoes}

---
_Generated by Gemini Code Reviewer (TS-Engine)_ ♟️
`.trim();
}